-- MySQL Script generated by MySQL Workbench
-- Sun Feb  4 22:21:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ressourcesrelationnelles
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ressourcesrelationnelles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ressourcesrelationnelles` DEFAULT CHARACTER SET utf8mb4 ;
USE `ressourcesrelationnelles` ;

-- -----------------------------------------------------
-- Table `ressourcesrelationnelles`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ressourcesrelationnelles`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ressourcesrelationnelles`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ressourcesrelationnelles`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `prenom` VARCHAR(100) NOT NULL,
  `adresse_mail` VARCHAR(255) NOT NULL,
  `mot_de_passe` VARCHAR(100) NOT NULL,
  `chemin_photo_profil` VARCHAR(255) NOT NULL,
  `date_desactive` DATETIME NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_utilisateur_role_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_utilisateur_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `ressourcesrelationnelles`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ressourcesrelationnelles`.`piece_jointe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ressourcesrelationnelles`.`piece_jointe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `chemin_piece_jointe` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ressourcesrelationnelles`.`ressource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ressourcesrelationnelles`.`ressource` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_publication` DATETIME NOT NULL,
  `date_modification` DATETIME NULL,
  `text` LONGTEXT NOT NULL,
  `visibilite` TINYINT NOT NULL,
  `valide` TINYINT NOT NULL,
  `nom_ressource` VARCHAR(255) NOT NULL,
  `utilisateur_id` INT NOT NULL,
  `piece_jointe_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ressource_utilisateur1_idx` (`utilisateur_id` ASC) VISIBLE,
  INDEX `fk_ressource_piece_jointe1_idx` (`piece_jointe_id` ASC) VISIBLE,
  CONSTRAINT `fk_ressource_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `ressourcesrelationnelles`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ressource_piece_jointe1`
    FOREIGN KEY (`piece_jointe_id`)
    REFERENCES `ressourcesrelationnelles`.`piece_jointe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ressourcesrelationnelles`.`type_parcours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ressourcesrelationnelles`.`type_parcours` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ressourcesrelationnelles`.`progression`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ressourcesrelationnelles`.`progression` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `utilisateur_id` INT NOT NULL,
  `ressource_id` INT NOT NULL,
  `type_parcours_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_progression_utilisateur1_idx` (`utilisateur_id` ASC) VISIBLE,
  INDEX `fk_progression_ressource1_idx` (`ressource_id` ASC) VISIBLE,
  INDEX `fk_progression_type_parcours1_idx` (`type_parcours_id` ASC) VISIBLE,
  CONSTRAINT `fk_progression_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `ressourcesrelationnelles`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_progression_ressource1`
    FOREIGN KEY (`ressource_id`)
    REFERENCES `ressourcesrelationnelles`.`ressource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_progression_type_parcours1`
    FOREIGN KEY (`type_parcours_id`)
    REFERENCES `ressourcesrelationnelles`.`type_parcours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ressourcesrelationnelles`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ressourcesrelationnelles`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(5000) NOT NULL,
  `date_envoi` DATETIME NOT NULL,
  `envoyeur` INT NOT NULL,
  `ressource_id` INT NOT NULL,
  `piece_jointe_id` INT NULL,
  `recepteur` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_utilisateur1_idx` (`envoyeur` ASC) VISIBLE,
  INDEX `fk_message_ressource1_idx` (`ressource_id` ASC) VISIBLE,
  INDEX `fk_message_piece_jointe1_idx` (`piece_jointe_id` ASC) VISIBLE,
  INDEX `fk_message_utilisateur2_idx` (`recepteur` ASC) VISIBLE,
  CONSTRAINT `fk_message_utilisateur1`
    FOREIGN KEY (`envoyeur`)
    REFERENCES `ressourcesrelationnelles`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_ressource1`
    FOREIGN KEY (`ressource_id`)
    REFERENCES `ressourcesrelationnelles`.`ressource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_piece_jointe1`
    FOREIGN KEY (`piece_jointe_id`)
    REFERENCES `ressourcesrelationnelles`.`piece_jointe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_utilisateur2`
    FOREIGN KEY (`recepteur`)
    REFERENCES `ressourcesrelationnelles`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ressourcesrelationnelles`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ressourcesrelationnelles`.`commentaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenu` LONGTEXT NOT NULL,
  `date_commentaire` DATETIME NOT NULL,
  `ressource_id` INT NOT NULL,
  `utilisateur_id` INT NOT NULL,
  `piece_jointe_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commentaire_ressource1_idx` (`ressource_id` ASC) VISIBLE,
  INDEX `fk_commentaire_utilisateur1_idx` (`utilisateur_id` ASC) VISIBLE,
  INDEX `fk_commentaire_piece_jointe1_idx` (`piece_jointe_id` ASC) VISIBLE,
  CONSTRAINT `fk_commentaire_ressource1`
    FOREIGN KEY (`ressource_id`)
    REFERENCES `ressourcesrelationnelles`.`ressource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaire_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `ressourcesrelationnelles`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaire_piece_jointe1`
    FOREIGN KEY (`piece_jointe_id`)
    REFERENCES `ressourcesrelationnelles`.`piece_jointe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ressourcesrelationnelles`.`reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ressourcesrelationnelles`.`reponse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reponse` TEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `piece_jointe_id` INT NULL,
  `commentaire_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reponse_piece_jointe1_idx` (`piece_jointe_id` ASC) VISIBLE,
  INDEX `fk_reponse_commentaire1_idx` (`commentaire_id` ASC) VISIBLE,
  CONSTRAINT `fk_reponse_piece_jointe1`
    FOREIGN KEY (`piece_jointe_id`)
    REFERENCES `ressourcesrelationnelles`.`piece_jointe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reponse_commentaire1`
    FOREIGN KEY (`commentaire_id`)
    REFERENCES `ressourcesrelationnelles`.`commentaire` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
